// <auto-generated />
using System;
using MainApp.EF.CodeFirst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MainApp.EF.CodeFirst.Migrations
{
    [DbContext(typeof(MainAppDatabaseContext))]
    [Migration("20190716141251_AddNumOfAllowedSearchesTable")]
    partial class AddNumOfAllowedSearchesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MainApp.EF.CodeFirst.CachedWords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnagramId");

                    b.Property<string>("Word")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("AnagramId");

                    b.ToTable("CachedWords");
                });

            modelBuilder.Entity("MainApp.EF.CodeFirst.NumOfAllowedSearches", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<string>("UserIp")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("NumOfAllowedSearches");
                });

            modelBuilder.Entity("MainApp.EF.CodeFirst.UserLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("SearchTime")
                        .HasColumnType("datetime");

                    b.Property<string>("UserIp")
                        .HasMaxLength(15);

                    b.Property<string>("Word")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("UserLog");
                });

            modelBuilder.Entity("MainApp.EF.CodeFirst.Words", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Word")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("MainApp.EF.CodeFirst.CachedWords", b =>
                {
                    b.HasOne("MainApp.EF.CodeFirst.Words", "Anagram")
                        .WithMany("CachedWords")
                        .HasForeignKey("AnagramId")
                        .HasConstraintName("FK_CachedWords_Words");
                });
#pragma warning restore 612, 618
        }
    }
}
